# Generated by Django 4.2.1 on 2023-05-31 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
