# Generated by Django 4.2.1 on 2023-06-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
